/**
 * Centralized error code constants for client-side localization
 * These codes are sent to the frontend to map to translated messages
 */
const ErrorCodes = {
  // Authentication (401)
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_PASSWORD_INCORRECT: 'AUTH_PASSWORD_INCORRECT',

  // Validation (400)
  VALIDATION_EMAIL_REQUIRED: 'VALIDATION_EMAIL_REQUIRED',
  VALIDATION_PASSWORD_REQUIRED: 'VALIDATION_PASSWORD_REQUIRED',
  VALIDATION_PASSWORD_TOO_SHORT: 'VALIDATION_PASSWORD_TOO_SHORT',
  VALIDATION_PASSWORD_MISMATCH: 'VALIDATION_PASSWORD_MISMATCH',

  // Rate limiting (429)
  RATE_LIMIT_LOGIN: 'RATE_LIMIT_LOGIN',
  RATE_LIMIT_PASSWORD: 'RATE_LIMIT_PASSWORD',

  // Not Found (404)
  NOT_FOUND_USER: 'NOT_FOUND_USER',

  // Conflict (409)
  CONFLICT_USER_EXISTS: 'CONFLICT_USER_EXISTS',
  CONFLICT_PASSWORD_EXISTS: 'CONFLICT_PASSWORD_EXISTS',
  CONFLICT_SETUP_COMPLETE: 'CONFLICT_SETUP_COMPLETE',

  // Generic codes (set as defaults in AppError.js)
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};

module.exports = { ErrorCodes };
